name: Daily Check-in

on:
  # schedule:
    # - cron: '43 3,9,13 * * *'
  workflow_dispatch:   # 支持手动触发测试

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          MOGUDING_AUTH: ${{ secrets.MOGUDING_AUTH }}
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          PLANID: ${{ secrets.PLANID }}
        run: python main.py
